### ISSUE TITLE
no matches for kind "Release" in version "jenkins.io/v1"

### ISSUE THREAD

**Issue by mdiloreto16** [salaboy/zeebe-operator#1]
Hey, I'm currently trying to get this operator running on my local machine but encountered this error after running:

`helm install zeebe-operator zeebe/zeebe-operator`

`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Release" in version "jenkins.io/v1"`

I've run helm repo update and my zeebe repo in helm is https://helm.zeebe.io.

I'm currently running kubernetes on my local machine through Docker for Desktop on a macbook.

Considering there isn't much for logs here I'm not 100% sure if this is an issue with my local cluster or the chart.

**Comment by salaboy** [comment]
@mdiloreto16 sorry about that, that should be fixed now.. if you do helm repo update and then install again it should work.. Thanks for reporting.

**Comment by mdiloreto16** [comment]
Thanks for the quick update! Just got it working now.

**Comment by salaboy** [comment]
@mdiloreto16 thanks for reporting.. keep an eye on my blog and the official Zeebe Blog .. because I am planning to move this code to the official org soon. If you want to contribute back as well please feel free to raise issues or features request here for now.
