### ISSUE TITLE
[FATAL tini (7)] exec /usr/local/bin/startup.sh failed: Permission denied

### ISSUE THREAD

**Issue by mdiloreto16** [salaboy/zeebe-operator#2]
Hi, had another go at getting the operator running on my local docker-kubernetes cluster, and am running into another issue. Helm installs the the zeebe-operator chart fine, and applying a ZeebeCluster works as well, however the zeebe-cluster pods seem to be having some issues. 

kc get all on zeebe-cluster ns: 

`pod/il-zeebe-cluster-zeebe-0   0/1     CrashLoopBackOff   6          9m45s`
`pod/il-zeebe-cluster-zeebe-1   0/1     CrashLoopBackOff   6          9m45s`
`pod/il-zeebe-cluster-zeebe-2   0/1     CrashLoopBackOff   6          9m45s`

pv's are created and pvc's are bound, elasticsearch pods are up and running, 
kc logs il-zeebe-cluster-zeebe-0:
`[FATAL tini (7)] exec /usr/local/bin/startup.sh failed: Permission denied`

I'm not sure if this is an issue caused by my cluster, or if this is something pertaining to the chart

**Comment by salaboy** [comment]
@mdiloreto16 that is interesting.. so you are running on Docker for Mac Kubernetes? or Windows? 
Let me try updating the version of the charts so you can try again with the latest versions.

**Comment by salaboy** [comment]
@mdiloreto16 ok.. updated.. now you should get Zeebe Cluster Helm 0.0.68.. can you please try again?

**Comment by mdiloreto16** [comment]
Hey @salaboy Just updated chart version, everything seems to be working now, thanks!
